import 'package:flutter/material.dart';

import 'decor_models.dart';

/// Rainy Library decoration pack: candlelight, ink, and quiet pages.
const rainyLibraryDecorItems = [
  StudyDecorItem(
    id: 'decor.rainyLibrary.greenLamp',
    title: 'Brass Reading Lamp',
    description: 'A classic library glow for the reading table.',
    cost: 90,
    themeId: 'rainyLibrary',
    icon: Icons.lightbulb,
    assetPath: 'assets/decor/generated/brass_desk_lamp_painterly_v1.png',
    baseScale: 0.20,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.46, 0.53),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.velvetChair',
    title: 'Vintage Clock',
    description: 'A brass clock for quiet reading blocks.',
    cost: 70,
    themeId: 'rainyLibrary',
    icon: Icons.access_time,
    assetPath: 'assets/decor/generated/vintage_clock_painterly_v1.png',
    baseScale: 0.19,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.18, 0.76),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.bookStack',
    title: 'Annotated Book Stack',
    description: 'Layered books and notes for rainy review blocks.',
    cost: 60,
    themeId: 'rainyLibrary',
    icon: Icons.menu_book,
    assetPath: 'assets/decor/generated/book_stack_painterly_v1.png',
    baseScale: 0.22,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.68, 0.67),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.readingGlasses',
    title: 'Reading Glasses',
    description: 'Round wire frames resting mid-chapter.',
    cost: 60,
    themeId: 'rainyLibrary',
    icon: Icons.visibility_outlined,
    assetPath: 'assets/decor/packs/rainyLibrary/reading_glasses.png',
    baseScale: 0.16,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.52, 0.70),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.teacup',
    title: 'Tea Cup & Saucer',
    description: 'Steam curling over a painted china cup.',
    cost: 70,
    themeId: 'rainyLibrary',
    icon: Icons.emoji_food_beverage_outlined,
    assetPath: 'assets/decor/packs/rainyLibrary/teacup.png',
    baseScale: 0.17,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.36, 0.68),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.oldJar',
    title: 'Old Glass Jar',
    description: 'A heavy jar keeping odds, ends, and secrets.',
    cost: 80,
    themeId: 'rainyLibrary',
    icon: Icons.science_outlined,
    assetPath: 'assets/decor/packs/rainyLibrary/old_jar.png',
    baseScale: 0.17,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.26, 0.72),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.candlestick',
    title: 'Brass Candlestick',
    description: 'A patient flame for grey afternoons.',
    cost: 90,
    themeId: 'rainyLibrary',
    icon: Icons.local_fire_department_outlined,
    assetPath: 'assets/decor/packs/rainyLibrary/candlestick.png',
    baseScale: 0.18,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.62, 0.60),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.inkwell',
    title: 'Pen & Inkwell',
    description: 'A dip pen beside a bottle of midnight ink.',
    cost: 100,
    themeId: 'rainyLibrary',
    icon: Icons.edit_outlined,
    assetPath: 'assets/decor/packs/rainyLibrary/inkwell.png',
    baseScale: 0.18,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.44, 0.64),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.sealedLetter',
    title: 'Wax-Sealed Letter',
    description: 'Folded parchment pressed with a crimson seal.',
    cost: 110,
    themeId: 'rainyLibrary',
    icon: Icons.mail_outline,
    assetPath: 'assets/decor/packs/rainyLibrary/sealed_letter.png',
    baseScale: 0.18,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.58, 0.70),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.parchmentRoll',
    title: 'Parchment Roll',
    description: 'A travel-worn scroll tied with twine.',
    cost: 120,
    themeId: 'rainyLibrary',
    icon: Icons.receipt_long_outlined,
    assetPath: 'assets/decor/packs/rainyLibrary/parchment_roll.png',
    baseScale: 0.19,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.70, 0.66),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.noticeBoard',
    title: 'Library Notice Board',
    description: 'Reading hours written in a careful hand.',
    cost: 320,
    themeId: 'rainyLibrary',
    icon: Icons.push_pin_outlined,
    assetPath: 'assets/decor/packs/rainyLibrary/notice_board.png',
    baseScale: 0.19,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.82, 0.62),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.hangingIvy',
    title: 'Hanging Ivy',
    description: 'Green trails spilling from a hanging pot.',
    cost: 340,
    themeId: 'rainyLibrary',
    icon: Icons.eco_outlined,
    assetPath: 'assets/decor/packs/rainyLibrary/hanging_ivy.png',
    baseScale: 0.23,
    rarity: DecorRarity.rare,
    zone: DecorZone.wall,
    defaultPosition: Offset(0.78, 0.26),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.tomeStack',
    title: 'Ancient Tome Stack',
    description: 'Leather spines stacked into a small tower.',
    cost: 360,
    themeId: 'rainyLibrary',
    icon: Icons.auto_stories_outlined,
    assetPath: 'assets/decor/packs/rainyLibrary/tome_stack.png',
    baseScale: 0.21,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.74, 0.70),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.quillSet',
    title: 'Quill Writing Set',
    description: 'A feather quill on its carved wooden tray.',
    cost: 380,
    themeId: 'rainyLibrary',
    icon: Icons.history_edu_outlined,
    assetPath: 'assets/decor/packs/rainyLibrary/quill_set.png',
    baseScale: 0.20,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.30, 0.66),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.cardCatalog',
    title: 'Card Catalog Chest',
    description: 'Tiny labeled drawers of everything ever read.',
    cost: 1500,
    themeId: 'rainyLibrary',
    icon: Icons.inventory_2_outlined,
    assetPath: 'assets/decor/packs/rainyLibrary/card_catalog.png',
    baseScale: 0.23,
    rarity: DecorRarity.epic,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.20, 0.66),
  ),
  StudyDecorItem(
    id: 'decor.rainyLibrary.raven',
    title: 'Midnight Raven',
    description: 'A watchful raven perched on forbidden volumes.',
    cost: 5200,
    themeId: 'rainyLibrary',
    icon: Icons.flutter_dash_outlined,
    assetPath: 'assets/decor/packs/rainyLibrary/raven.png',
    baseScale: 0.22,
    rarity: DecorRarity.legendary,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.82, 0.56),
  ),
];
