import 'package:flutter/material.dart';

import 'decor_models.dart';

/// Midnight City decoration pack: late-night desk tech and neon warmth.
const midnightCityDecorItems = [
  StudyDecorItem(
    id: 'decor.midnightCity.neonSign',
    title: 'Monitor Light',
    description: 'A warm screen bar for late-night focus.',
    cost: 100,
    themeId: 'midnightCity',
    icon: Icons.light,
    assetPath: 'assets/decor/generated/monitor_light_painterly_v1.png',
    baseScale: 0.23,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.76, 0.20),
  ),
  StudyDecorItem(
    id: 'decor.midnightCity.dualMonitor',
    title: 'Mechanical Keyboard',
    description: 'A compact keyboard with cozy city-desk glow.',
    cost: 120,
    themeId: 'midnightCity',
    icon: Icons.desktop_windows,
    assetPath: 'assets/decor/generated/mechanical_keyboard_painterly_v1.png',
    baseScale: 0.25,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.46, 0.52),
  ),
  StudyDecorItem(
    id: 'decor.midnightCity.deskCar',
    title: 'Headphones',
    description: 'Soft brown headphones for night coding sessions.',
    cost: 60,
    themeId: 'midnightCity',
    icon: Icons.headphones,
    assetPath: 'assets/decor/generated/headphones_painterly_v1.png',
    baseScale: 0.20,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.28, 0.72),
  ),
  StudyDecorItem(
    id: 'decor.midnightCity.blackCoffee',
    title: 'Midnight Espresso',
    description: 'Black coffee in a dark cup with gold trim.',
    cost: 70,
    themeId: 'midnightCity',
    icon: Icons.coffee_outlined,
    assetPath: 'assets/decor/packs/midnightCity/black_coffee.png',
    baseScale: 0.15,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.36, 0.68),
  ),
  StudyDecorItem(
    id: 'decor.midnightCity.cityPlant',
    title: 'Desk Plant',
    description: 'Glossy leaves that thrive on lamplight.',
    cost: 90,
    themeId: 'midnightCity',
    icon: Icons.local_florist_outlined,
    assetPath: 'assets/decor/packs/midnightCity/city_plant.png',
    baseScale: 0.17,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.72, 0.60),
  ),
  StudyDecorItem(
    id: 'decor.midnightCity.plannerNotebook',
    title: 'Night Planner',
    description: 'A spiral planner with tomorrow already sketched.',
    cost: 100,
    themeId: 'midnightCity',
    icon: Icons.book_outlined,
    assetPath: 'assets/decor/packs/midnightCity/planner_notebook.png',
    baseScale: 0.16,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.56, 0.70),
  ),
  StudyDecorItem(
    id: 'decor.midnightCity.gamingMouse',
    title: 'Gaming Mouse',
    description: 'A quiet glow tracing its sculpted edge.',
    cost: 120,
    themeId: 'midnightCity',
    icon: Icons.mouse_outlined,
    assetPath: 'assets/decor/packs/midnightCity/gaming_mouse.png',
    baseScale: 0.14,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.60, 0.64),
  ),
  StudyDecorItem(
    id: 'decor.midnightCity.laptopStand',
    title: 'Laptop Stand',
    description: 'A folded metal perch for better posture.',
    cost: 140,
    themeId: 'midnightCity',
    icon: Icons.laptop_outlined,
    assetPath: 'assets/decor/packs/midnightCity/laptop_stand.png',
    baseScale: 0.18,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.30, 0.62),
  ),
  StudyDecorItem(
    id: 'decor.midnightCity.deskLampLed',
    title: 'Fold-Arm Desk Lamp',
    description: 'An articulated lamp angled just right.',
    cost: 350,
    themeId: 'midnightCity',
    icon: Icons.tungsten_outlined,
    assetPath: 'assets/decor/packs/midnightCity/led_desk_lamp.png',
    baseScale: 0.18,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.20, 0.56),
  ),
  StudyDecorItem(
    id: 'decor.midnightCity.smartSpeaker',
    title: 'Smart Speaker',
    description: 'Lo-fi beats from a ring of soft blue light.',
    cost: 380,
    themeId: 'midnightCity',
    icon: Icons.speaker_outlined,
    assetPath: 'assets/decor/packs/midnightCity/smart_speaker.png',
    baseScale: 0.15,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.68, 0.58),
  ),
  StudyDecorItem(
    id: 'decor.midnightCity.cityFrame',
    title: 'Skyline Photo Frame',
    description: 'The city at golden hour, framed in black.',
    cost: 420,
    themeId: 'midnightCity',
    icon: Icons.photo_outlined,
    assetPath: 'assets/decor/packs/midnightCity/city_frame.png',
    baseScale: 0.17,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.44, 0.58),
  ),
  StudyDecorItem(
    id: 'decor.midnightCity.neonCupSign',
    title: 'Neon Coffee Sign',
    description: 'A glowing cup that never needs a refill.',
    cost: 1500,
    themeId: 'midnightCity',
    icon: Icons.emoji_objects_outlined,
    assetPath: 'assets/decor/packs/midnightCity/neon_cup_sign.png',
    baseScale: 0.17,
    rarity: DecorRarity.epic,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.82, 0.54),
  ),
  StudyDecorItem(
    id: 'decor.midnightCity.ultrawideMonitor',
    title: 'Ultrawide Monitor',
    description: 'A curved horizon of rainy skyline pixels.',
    cost: 5000,
    themeId: 'midnightCity',
    icon: Icons.monitor_outlined,
    assetPath: 'assets/decor/packs/midnightCity/ultrawide_monitor.png',
    baseScale: 0.24,
    rarity: DecorRarity.legendary,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.50, 0.52),
  ),
];
