import 'package:flutter/material.dart';

import 'decor_models.dart';

/// Grand Archive decoration pack: brass, parchment, and scholarly relics.
const grandArchiveDecorItems = [
  StudyDecorItem(
    id: 'decor.grandArchive.brassLamp',
    title: 'Archive Lamp',
    description: 'A brass lamp for long reading tables.',
    cost: 100,
    themeId: 'grandArchive',
    icon: Icons.light,
    assetPath: 'assets/decor/generated/brass_desk_lamp_painterly_v1.png',
    baseScale: 0.22,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.22, 0.56),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.bookStack',
    title: 'Rare Book Stack',
    description: 'Leather-bound references for deep research.',
    cost: 70,
    themeId: 'grandArchive',
    icon: Icons.menu_book,
    assetPath: 'assets/decor/generated/book_stack_painterly_v1.png',
    baseScale: 0.22,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.58, 0.68),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.plant',
    title: 'Pen Holder',
    description: 'A carved desk cup with pens for archive notes.',
    cost: 70,
    themeId: 'grandArchive',
    icon: Icons.edit,
    assetPath: 'assets/decor/generated/pen_holder_painterly_v1.png',
    baseScale: 0.20,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.78, 0.55),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.clock',
    title: 'Vintage Clock',
    description: 'A warm brass clock for timeless study sessions.',
    cost: 80,
    themeId: 'grandArchive',
    icon: Icons.access_time,
    assetPath: 'assets/decor/generated/vintage_clock_painterly_v1.png',
    baseScale: 0.19,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.62, 0.70),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.magnifier',
    title: 'Brass Magnifier',
    description: 'For footnotes written smaller than doubt.',
    cost: 90,
    themeId: 'grandArchive',
    icon: Icons.search,
    assetPath: 'assets/decor/packs/grandArchive/magnifier.png',
    baseScale: 0.17,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.40, 0.68),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.quillCup',
    title: 'Brass Quill Cup',
    description: 'Quills and dip pens in an engraved cup.',
    cost: 100,
    themeId: 'grandArchive',
    icon: Icons.history_edu_outlined,
    assetPath: 'assets/decor/packs/grandArchive/quill_cup.png',
    baseScale: 0.17,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.66, 0.64),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.parchmentBundle',
    title: 'Parchment Bundle',
    description: 'Centuries of notes tied with leather cord.',
    cost: 120,
    themeId: 'grandArchive',
    icon: Icons.description_outlined,
    assetPath: 'assets/decor/packs/grandArchive/parchment_bundle.png',
    baseScale: 0.20,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.48, 0.72),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.sealedScroll',
    title: 'Sealed Scroll',
    description: 'Rolled vellum pressed with a crimson seal.',
    cost: 140,
    themeId: 'grandArchive',
    icon: Icons.approval_outlined,
    assetPath: 'assets/decor/packs/grandArchive/sealed_scroll.png',
    baseScale: 0.19,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.30, 0.64),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.manuscript',
    title: "Scholar's Manuscript",
    description: 'An open page mid-thought, quill still wet.',
    cost: 340,
    themeId: 'grandArchive',
    icon: Icons.article_outlined,
    assetPath: 'assets/decor/packs/grandArchive/manuscript.png',
    baseScale: 0.20,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.56, 0.62),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.cartographerCompass',
    title: "Cartographer's Compass",
    description: 'A brass compass that has mapped lost shelves.',
    cost: 360,
    themeId: 'grandArchive',
    icon: Icons.explore_outlined,
    assetPath: 'assets/decor/packs/grandArchive/cartographer_compass.png',
    baseScale: 0.17,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.70, 0.58),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.hourglass',
    title: 'Amber Hourglass',
    description: 'Golden sand measuring patient hours.',
    cost: 380,
    themeId: 'grandArchive',
    icon: Icons.hourglass_bottom,
    assetPath: 'assets/decor/packs/grandArchive/hourglass.png',
    baseScale: 0.18,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.36, 0.60),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.bankersLamp',
    title: "Emerald Banker's Lamp",
    description: 'Green glass pouring gold light on parchment.',
    cost: 400,
    themeId: 'grandArchive',
    icon: Icons.tungsten_outlined,
    assetPath: 'assets/decor/packs/grandArchive/bankers_lamp.png',
    baseScale: 0.20,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.24, 0.56),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.bellLamp',
    title: 'Brass Bell Lamp',
    description: 'A curved-arm lamp from an older reading room.',
    cost: 420,
    themeId: 'grandArchive',
    icon: Icons.light_outlined,
    assetPath: 'assets/decor/packs/grandArchive/bell_lamp.png',
    baseScale: 0.20,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.16, 0.62),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.catalogCabinet',
    title: 'Catalog Cabinet',
    description: 'Tiny labeled drawers of indexed knowledge.',
    cost: 460,
    themeId: 'grandArchive',
    icon: Icons.inventory_2_outlined,
    assetPath: 'assets/decor/packs/grandArchive/catalog_cabinet.png',
    baseScale: 0.22,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.84, 0.66),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.brassTelescope',
    title: 'Brass Telescope',
    description: 'A collapsible spyglass on a turned stand.',
    cost: 520,
    themeId: 'grandArchive',
    icon: Icons.search_outlined,
    assetPath: 'assets/decor/packs/grandArchive/brass_telescope.png',
    baseScale: 0.22,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.78, 0.52),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.mapFrame',
    title: "Cartographer's Map",
    description: 'An antique world map in a gilt frame.',
    cost: 1500,
    themeId: 'grandArchive',
    icon: Icons.map_outlined,
    assetPath: 'assets/decor/packs/grandArchive/map_frame.png',
    baseScale: 0.23,
    rarity: DecorRarity.epic,
    zone: DecorZone.wall,
    defaultPosition: Offset(0.30, 0.28),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.scholarPlaque',
    title: 'Laureate Plaque',
    description: 'Gilded laurels honoring a true streak-keeper.',
    cost: 1600,
    themeId: 'grandArchive',
    icon: Icons.military_tech_outlined,
    assetPath: 'assets/decor/packs/grandArchive/scholar_plaque.png',
    baseScale: 0.19,
    rarity: DecorRarity.epic,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.50, 0.56),
  ),
  StudyDecorItem(
    id: 'decor.grandArchive.antiqueGlobe',
    title: 'Antique World Globe',
    description: 'A weathered sphere of faded gold continents.',
    cost: 5200,
    themeId: 'grandArchive',
    icon: Icons.public,
    assetPath: 'assets/decor/packs/grandArchive/antique_globe.png',
    baseScale: 0.24,
    rarity: DecorRarity.legendary,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.84, 0.56),
  ),
];
