import 'package:flutter/material.dart';

import 'decor_models.dart';

/// Cozy Cafe decoration pack: warm counter clutter, pastries, and jazz.
const cozyCafeDecorItems = [
  StudyDecorItem(
    id: 'decor.cozyCafe.mug',
    title: 'Cozy Mug',
    description: 'A warm table mug for the cafe desk.',
    cost: 50,
    themeId: 'cozyCafe',
    icon: Icons.coffee,
    assetPath: 'assets/decor/generated/coffee_mug_painterly_v1.png',
    baseScale: 0.17,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.57, 0.66),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.brassLamp',
    title: 'Brass Desk Lamp',
    description: 'A focused amber cone light for late cafe sessions.',
    cost: 80,
    themeId: 'cozyCafe',
    icon: Icons.light,
    assetPath: 'assets/decor/generated/brass_desk_lamp_painterly_v1.png',
    baseScale: 0.23,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.20, 0.18),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.pastryTray',
    title: 'Pastry Tray',
    description: 'Croissants and cafe snacks for the front counter.',
    cost: 70,
    themeId: 'cozyCafe',
    icon: Icons.bakery_dining,
    assetPath: 'assets/decor/generated/pastry_plate_painterly_v1.png',
    baseScale: 0.21,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.24, 0.74),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.espressoCup',
    title: 'Espresso Cup',
    description: 'A bold little shot in two-tone ceramic.',
    cost: 50,
    themeId: 'cozyCafe',
    icon: Icons.coffee_outlined,
    assetPath: 'assets/decor/packs/cozyCafe/espresso_cup.png',
    baseScale: 0.15,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.52, 0.66),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.steamingCappuccino',
    title: 'Steaming Cappuccino',
    description: 'Foam art still swirling under the steam.',
    cost: 60,
    themeId: 'cozyCafe',
    icon: Icons.local_cafe_outlined,
    assetPath: 'assets/decor/packs/cozyCafe/steaming_cappuccino.png',
    baseScale: 0.16,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.62, 0.68),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.beanJar',
    title: 'Coffee Bean Jar',
    description: 'A corked glass jar of fresh roasted beans.',
    cost: 70,
    themeId: 'cozyCafe',
    icon: Icons.coffee_maker_outlined,
    assetPath: 'assets/decor/packs/cozyCafe/bean_jar.png',
    baseScale: 0.16,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.70, 0.62),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.honeyJar',
    title: 'Honey Jar',
    description: 'Golden honey with a tiny wooden dipper.',
    cost: 80,
    themeId: 'cozyCafe',
    icon: Icons.hive_outlined,
    assetPath: 'assets/decor/packs/cozyCafe/honey_jar.png',
    baseScale: 0.15,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.34, 0.66),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.pottedHerb',
    title: 'Potted Herb',
    description: 'Fresh green leaves in a clay cafe pot.',
    cost: 90,
    themeId: 'cozyCafe',
    icon: Icons.local_florist_outlined,
    assetPath: 'assets/decor/packs/cozyCafe/potted_herb.png',
    baseScale: 0.17,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.76, 0.58),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.cafeReadingSet',
    title: 'Cafe Reading Set',
    description: 'A cappuccino resting against well-read spines.',
    cost: 110,
    themeId: 'cozyCafe',
    icon: Icons.menu_book_outlined,
    assetPath: 'assets/decor/packs/cozyCafe/cafe_reading_set.png',
    baseScale: 0.18,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.44, 0.70),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.alarmClock',
    title: 'Brass Alarm Clock',
    description: 'A round-faced keeper of cafe hours.',
    cost: 120,
    themeId: 'cozyCafe',
    icon: Icons.alarm,
    assetPath: 'assets/decor/packs/cozyCafe/alarm_clock.png',
    baseScale: 0.16,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.28, 0.60),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.bookBundle',
    title: 'Tied Book Bundle',
    description: 'Vintage volumes wrapped in twine and stories.',
    cost: 130,
    themeId: 'cozyCafe',
    icon: Icons.auto_stories_outlined,
    assetPath: 'assets/decor/packs/cozyCafe/book_bundle.png',
    baseScale: 0.18,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.66, 0.70),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.chalkboardEasel',
    title: 'Standing Chalkboard',
    description: 'Today’s specials in looping chalk script.',
    cost: 320,
    themeId: 'cozyCafe',
    icon: Icons.edit_note,
    assetPath: 'assets/decor/packs/cozyCafe/chalkboard_easel.png',
    baseScale: 0.18,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.18, 0.58),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.menuBoard',
    title: 'Cafe Menu Board',
    description: 'Chalk specials beside a tiny warm candle.',
    cost: 360,
    themeId: 'cozyCafe',
    icon: Icons.storefront_outlined,
    assetPath: 'assets/decor/packs/cozyCafe/menu_board.png',
    baseScale: 0.20,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.82, 0.52),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.strawberryTart',
    title: 'Strawberry Tart',
    description: 'A glossy tart that deserves its own plate.',
    cost: 400,
    themeId: 'cozyCafe',
    icon: Icons.cake_outlined,
    assetPath: 'assets/decor/packs/cozyCafe/strawberry_tart.png',
    baseScale: 0.17,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.48, 0.72),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.coffeeGrinder',
    title: 'Antique Coffee Grinder',
    description: 'A hand-crank grinder with a walnut drawer.',
    cost: 450,
    themeId: 'cozyCafe',
    icon: Icons.coffee_maker,
    assetPath: 'assets/decor/packs/cozyCafe/coffee_grinder.png',
    baseScale: 0.18,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.24, 0.68),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.jazzRecords',
    title: 'Jazz Records',
    description: 'A leaning sleeve of late-night standards.',
    cost: 1500,
    themeId: 'cozyCafe',
    icon: Icons.album_outlined,
    assetPath: 'assets/decor/packs/cozyCafe/jazz_records.png',
    baseScale: 0.17,
    rarity: DecorRarity.epic,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.58, 0.60),
  ),
  StudyDecorItem(
    id: 'decor.cozyCafe.recordCabinet',
    title: 'Jazz Radio Console',
    description: 'A wooden console that hums with soft jazz.',
    cost: 5000,
    themeId: 'cozyCafe',
    icon: Icons.radio_outlined,
    assetPath: 'assets/decor/packs/cozyCafe/record_cabinet.png',
    baseScale: 0.22,
    rarity: DecorRarity.legendary,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.16, 0.62),
  ),
];
