import 'package:flutter/material.dart';

import 'decor_models.dart';

/// Garden Matcha decoration pack: stone, tea, blossom, and calm water.
const gardenMatchaDecorItems = [
  StudyDecorItem(
    id: 'decor.gardenMatcha.fern',
    title: 'Booth Fern',
    description: 'Soft green leaves for the glass cafe corner.',
    cost: 70,
    themeId: 'gardenMatcha',
    icon: Icons.local_florist,
    assetPath: 'assets/decor/generated/potted_plant_painterly_v1.png',
    baseScale: 0.23,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.80, 0.55),
  ),
  StudyDecorItem(
    id: 'decor.gardenMatcha.matchaCup',
    title: 'Iced Matcha',
    description: 'A calm green drink on the laptop table.',
    cost: 50,
    themeId: 'gardenMatcha',
    icon: Icons.local_drink,
    assetPath: 'assets/decor/generated/matcha_cup_painterly_v1.png',
    baseScale: 0.18,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.42, 0.67),
  ),
  StudyDecorItem(
    id: 'decor.gardenMatcha.earbuds',
    title: 'Candle',
    description: 'A tiny warm flame for a calm green desk.',
    cost: 60,
    themeId: 'gardenMatcha',
    icon: Icons.local_fire_department,
    assetPath: 'assets/decor/generated/candle_painterly_v1.png',
    baseScale: 0.16,
    rarity: DecorRarity.common,
    zone: DecorZone.free,
    defaultPosition: Offset(0.30, 0.72),
  ),
  StudyDecorItem(
    id: 'decor.gardenMatcha.matchaBowl',
    title: 'Matcha Bowl',
    description: 'Stone-glazed ceramic with whisked green tea.',
    cost: 60,
    themeId: 'gardenMatcha',
    icon: Icons.ramen_dining_outlined,
    assetPath: 'assets/decor/packs/gardenMatcha/matcha_bowl.png',
    baseScale: 0.15,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.46, 0.68),
  ),
  StudyDecorItem(
    id: 'decor.gardenMatcha.bambooWhisk',
    title: 'Bamboo Whisk Set',
    description: 'A chasen and scoop carved from pale bamboo.',
    cost: 70,
    themeId: 'gardenMatcha',
    icon: Icons.brush_outlined,
    assetPath: 'assets/decor/packs/gardenMatcha/bamboo_whisk.png',
    baseScale: 0.15,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.56, 0.70),
  ),
  StudyDecorItem(
    id: 'decor.gardenMatcha.stoneCandle',
    title: 'Stone Candle',
    description: 'A round stone cup holding a steady flame.',
    cost: 80,
    themeId: 'gardenMatcha',
    icon: Icons.local_fire_department_outlined,
    assetPath: 'assets/decor/packs/gardenMatcha/stone_candle.png',
    baseScale: 0.14,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.34, 0.66),
  ),
  StudyDecorItem(
    id: 'decor.gardenMatcha.sakuraBowl',
    title: 'Sakura Blossom Bowl',
    description: 'Blush petals arranged in a stone dish.',
    cost: 100,
    themeId: 'gardenMatcha',
    icon: Icons.filter_vintage_outlined,
    assetPath: 'assets/decor/packs/gardenMatcha/sakura_bowl.png',
    baseScale: 0.17,
    rarity: DecorRarity.common,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.66, 0.62),
  ),
  StudyDecorItem(
    id: 'decor.gardenMatcha.sakuraBranch',
    title: 'Sakura Branch',
    description: 'A cherry branch resting in full bloom.',
    cost: 320,
    themeId: 'gardenMatcha',
    icon: Icons.park_outlined,
    assetPath: 'assets/decor/packs/gardenMatcha/sakura_branch.png',
    baseScale: 0.18,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.74, 0.66),
  ),
  StudyDecorItem(
    id: 'decor.gardenMatcha.koiTray',
    title: 'Koi Zen Tray',
    description: 'A painted koi gliding across raked sand.',
    cost: 380,
    themeId: 'gardenMatcha',
    icon: Icons.set_meal_outlined,
    assetPath: 'assets/decor/packs/gardenMatcha/koi_tray.png',
    baseScale: 0.19,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.40, 0.72),
  ),
  StudyDecorItem(
    id: 'decor.gardenMatcha.bambooFountain',
    title: 'Bamboo Fountain',
    description: 'A gentle clack of water on smooth stone.',
    cost: 480,
    themeId: 'gardenMatcha',
    icon: Icons.water_drop_outlined,
    assetPath: 'assets/decor/packs/gardenMatcha/bamboo_fountain.png',
    baseScale: 0.20,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.20, 0.64),
  ),
  StudyDecorItem(
    id: 'decor.gardenMatcha.teaSetTray',
    title: 'Tea Ceremony Set',
    description: 'A celadon pot and cups on a wooden tray.',
    cost: 520,
    themeId: 'gardenMatcha',
    icon: Icons.emoji_food_beverage_outlined,
    assetPath: 'assets/decor/packs/gardenMatcha/tea_set_tray.png',
    baseScale: 0.20,
    rarity: DecorRarity.rare,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.50, 0.74),
  ),
  StudyDecorItem(
    id: 'decor.gardenMatcha.stoneLantern',
    title: 'Glowing Stone Lantern',
    description: 'A pagoda lantern warming the moss at dusk.',
    cost: 1500,
    themeId: 'gardenMatcha',
    icon: Icons.temple_buddhist_outlined,
    assetPath: 'assets/decor/packs/gardenMatcha/stone_lantern.png',
    baseScale: 0.20,
    rarity: DecorRarity.epic,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.82, 0.60),
  ),
  StudyDecorItem(
    id: 'decor.gardenMatcha.bonsai',
    title: 'Ancient Bonsai',
    description: 'A windswept pine shaped by a hundred springs.',
    cost: 5000,
    themeId: 'gardenMatcha',
    icon: Icons.park,
    assetPath: 'assets/decor/packs/gardenMatcha/bonsai.png',
    baseScale: 0.21,
    rarity: DecorRarity.legendary,
    zone: DecorZone.desk,
    defaultPosition: Offset(0.16, 0.58),
  ),
];
